### PR TITLE
I made some changes as per your instructions. For your review please.

### PR DESCRIPTION
**Pull request by vijayverma31aug**
From tester.

This is to inform you that i have completed the task. Please review the code.

With regards,
 
Vijay Kumar Verma
Tester

### CODE REVIEW

**Review by Ankit-Kum — COMMENTED** [review]
changes looks fine and more dis about varibles

**Comment by Ankit-Kum** [comment]
hi vijay 👍 do one thing explain more about the variable and write m or line of code

regards 
Ankit 
Lead

**Comment by vijayverma31aug** [comment]
This is done from my side. Kindly review it.

**Review by Ankit-Kum — COMMENTED** [review]
so every thing looks nice. now i am meragi g your code with the project

**Pull request merged**
